# stage1 - build react app first 
FROM node:12.16.1-alpine3.9 as build

WORKDIR /frontend

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm ci --production

COPY . .

RUN npm run build

# stage 2 - Nginx
FROM nginx:1.17.8-alpine

COPY --from=build /frontend/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf


EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
