version: '3.7'

services:

  rahnama-front-prod:
    container_name: rahnama-front-prod-cont
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'

networks:
  g5_default:
    external: true
