version: "3.8"

services:

  nginx:
    image: docker.abrman.ir/web_server/nginx:1.17.8-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend:/usr/share/nginx/html

    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - frontend

  frontend:
    container_name: frontend
    image: docker.abrman.ir/g5/frontend:55d6966
    volumes:
      - frontend:/frontend/build

volumes:
  frontend:
